# Data Analytics Final Project
## Superstore E-Commerce Sales Analysis Using Python

This notebook performs end-to-end exploratory data analysis (EDA) on a Superstore E-Commerce dataset to understand sales performance, product profitability, and regional trends.

## 1. Import Required Libraries

In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 2. Load Dataset

In [26]:
df = pd.read_csv('superstore_ecommerce_sample.csv')
# Display dataset
print("Dataset Preview:")
print(df)

Dataset Preview:
      Row ID   Order ID  Order Date   Ship Date     Ship Mode Customer ID  \
0          1  ORD-10000  2022-04-13  2022-04-19      Same Day   CUST-1725
1          2  ORD-10001  2023-03-12  2023-03-15      Same Day   CUST-6202
2          3  ORD-10002  2022-09-28  2022-09-30   First Class   CUST-9082
3          4  ORD-10003  2022-04-17  2022-04-18   First Class   CUST-7893
4          5  ORD-10004  2022-03-13  2022-03-19  Second Class   CUST-7188
...      ...        ...         ...         ...           ...         ...
1195    1196  ORD-11195  2023-11-01  2023-11-07  Second Class   CUST-5289
1196    1197  ORD-11196  2022-10-12  2022-10-14   First Class   CUST-3807
1197    1198  ORD-11197  2022-11-01  2022-11-02      Same Day   CUST-6542
1198    1199  ORD-11198  2023-03-05  2023-03-10   First Class   CUST-5577
1199    1200  ORD-11199  2023-04-22  2023-04-26      Same Day   CUST-2744

     Customer Name    Segment Country       City  ... Postal Code  Region  \
0     Customer_475  Corporate   India  Bangalore  ...      626632   South
1     Customer_118   Consumer   India      Delhi  ...      623864   North
2     Customer_136   Consumer   India  Bangalore  ...      655779   North
3     Customer_316  Corporate   India      Kochi  ...      604654   North
4     Customer_331  Corporate   India  Hyderabad  ...      673253   North
...            ...        ...     ...        ...  ...         ...     ...
1195  Customer_429  Corporate   India    Chennai  ...      676271   North
1196  Customer_226   Consumer   India  Bangalore  ...      643028    West
1197  Customer_407   Consumer   India     Mumbai  ...      685642    West
1198  Customer_449   Consumer   India     Mumbai  ...      676056   South
1199  Customer_312   Consumer   India      Delhi  ...      649432    West

     Product ID         Category Sub-Category     Product Name    Sales  \
0      PROD-753       Technology     Machines          Scanner   964.66
1      PROD-152  Office Supplies        Paper    A4 Paper Pack  1655.02
2      PROD-302  Office Supplies        Paper    Notebook Pack  2028.37
3      PROD-387       Technology  Accessories         Keyboard  2858.25
4      PROD-777        Furniture       Chairs  Executive Chair  1542.58
...         ...              ...          ...              ...      ...
1195   PROD-954  Office Supplies        Paper    A4 Paper Pack   682.70
1196   PROD-913        Furniture       Chairs  Executive Chair  2355.58
1197   PROD-630        Furniture    Bookcases    Wood Bookcase  3338.18
1198   PROD-680       Technology  Accessories          USB Hub   711.79
1199   PROD-284       Technology  Accessories            Mouse  3879.66

      Quantity  Discount  Profit
0            6      0.02  125.41
1            4      0.08  115.85
2            2      0.10  101.42
3            9      0.09  171.50
4            4      0.28 -200.54
...        ...       ...     ...
1195         2      0.12   20.48
1196         4      0.17  -47.11
1197         6      0.11  133.53
1198         8      0.11   28.47
1199         7      0.29 -543.15

[1200 rows x 21 columns]

## 3. Dataset Overview

In [27]:
print("\nNumber of rows =", df.shape[0])
print("Number of columns =", df.shape[1])

Number of rows = 1200
Number of columns = 21

In [28]:
print("\nFirst 5 rows:")
print(df.head())

First 5 rows:
   Row ID   Order ID  Order Date   Ship Date     Ship Mode Customer ID  \
0       1  ORD-10000  2022-04-13  2022-04-19      Same Day   CUST-1725
1       2  ORD-10001  2023-03-12  2023-03-15      Same Day   CUST-6202
2       3  ORD-10002  2022-09-28  2022-09-30   First Class   CUST-9082
3       4  ORD-10003  2022-04-17  2022-04-18   First Class   CUST-7893
4       5  ORD-10004  2022-03-13  2022-03-19  Second Class   CUST-7188

  Customer Name    Segment Country       City  ... Postal Code  Region  \
0  Customer_475  Corporate   India  Bangalore  ...      626632   South
1  Customer_118   Consumer   India      Delhi  ...      623864   North
2  Customer_136   Consumer   India  Bangalore  ...      655779   North
3  Customer_316  Corporate   India      Kochi  ...      604654   North
4  Customer_331  Corporate   India  Hyderabad  ...      673253   North

  Product ID         Category Sub-Category     Product Name    Sales  \
0   PROD-753       Technology     Machines          Scanner   964.66
1   PROD-152  Office Supplies        Paper    A4 Paper Pack  1655.02
2   PROD-302  Office Supplies        Paper    Notebook Pack  2028.37
3   PROD-387       Technology  Accessories         Keyboard  2858.25
4   PROD-777        Furniture       Chairs  Executive Chair  1542.58

   Quantity  Discount  Profit
0         6      0.02  125.41
1         4      0.08  115.85
2         2      0.10  101.42
3         9      0.09  171.50
4         4      0.28 -200.54

[5 rows x 21 columns]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         1200 non-null   int64
 1   Order ID       1200 non-null   object
 2   Order Date     1200 non-null   object
 3   Ship Date      1200 non-null   object
 4   Ship Mode      1200 non-null   object
 5   Customer ID    1200 non-null   object
 6   Customer Name  1200 non-null   object
 7   Segment        1200 non-null   object
 8   Country        1200 non-null   object
 9   City           1200 non-null   object
 10  State          1200 non-null   object
 11  Postal Code    1200 non-null   int64
 12  Region         1200 non-null   object
 13  Product ID     1200 non-null   object
 14  Category       1200 non-null   object
 15  Sub-Category   1200 non-null   object
 16  Product Name   1200 non-null   object
 17  Sales          1200 non-null   float64
 18  Quantity       1200 non-null   int64
 19  Discount       1200 non-null   float64
 20  Profit         1200 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 126.6+ KB

In [30]:
print("\nLast 5 rows:")
df.tail()

Last 5 rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1195,1196,ORD-11195,2023-11-01,2023-11-07,Second Class,CUST-5289,Customer_429,Corporate,India,Chennai,...,676271,North,PROD-954,Office Supplies,Paper,A4 Paper Pack,682.70,2,0.12,20.48
1196,1197,ORD-11196,2022-10-12,2022-10-14,First Class,CUST-3807,Customer_226,Consumer,India,Bangalore,...,643028,West,PROD-913,Furniture,Chairs,Executive Chair,2355.58,4,0.17,-47.11
1197,1198,ORD-11197,2022-11-01,2022-11-02,Same Day,CUST-6542,Customer_407,Consumer,India,Mumbai,...,685642,West,PROD-630,Furniture,Bookcases,Wood Bookcase,3338.18,6,0.11,133.53
1198,1199,ORD-11198,2023-03-05,2023-03-10,First Class,CUST-5577,Customer_449,Consumer,India,Mumbai,...,676056,South,PROD-680,Technology,Accessories,USB Hub,711.79,8,0.11,28.47
1199,1200,ORD-11199,2023-04-22,2023-04-26,Same Day,CUST-2744,Customer_312,Consumer,India,Delhi,...,649432,West,PROD-284,Technology,Accessories,Mouse,3879.66,7,0.29,-543.15

In [31]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,600.500000,650850.573333,2539.985742,4.996667,0.146183,10.561208
std,346.554469,29483.927437,1391.145402,2.590157,0.086213,247.303284
min,1.000000,600112.000000,201.600000,1.000000,0.000000,-670.740000
25%,300.750000,625061.500000,1314.432500,3.000000,0.070000,-130.170000
50%,600.500000,651720.500000,2487.865000,5.000000,0.150000,0.000000
75%,900.250000,677059.000000,3733.265000,7.000000,0.220000,144.930000
max,1200.000000,699946.000000,4989.540000,9.000000,0.300000,739.780000

## 4. Data Cleaning

## CHECKING MISSING VALUES

In [32]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

## HANDLING MISSING VALUES

In [33]:
df.ffill(inplace=True)

## REMOVE DUPLICATE RECORDS

In [34]:
df.drop_duplicates(inplace=True)

## Convert Date Columns

In [43]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Country                   object
City                      object
State                     object
Postal Code                int64
Region                    object
Product ID                object
Category                  object
Sub-Category              object
Product Name              object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Year                       int32
Month                      int32
Sales_Category          category
dtype: object

## Create Derived Columns

## EXTRACT YEAR

In [36]:
df['Year'] = df['Order Date'].dt.year

## Extract Month

In [37]:
df['Month'] = df['Order Date'].dt.month

## Sales Category

In [38]:
df['Sales_Category'] = pd.cut(df['Sales'],
                             bins=[0,500,2000,5000],
                             labels=['Low','Medium','High'])

## Filtering Example

In [44]:
high_profit = df[df['Profit'] > 500]

## Aggregation Example

In [40]:
df.groupby('Category')['Sales'].sum()

Category
Furniture           963869.48
Office Supplies    1018727.78
Technology         1065385.63
Name: Sales, dtype: float64